### PR TITLE
Modify CSS of Flash messages

### LINKED ISSUE #12: Improve CSS of Flash Messages.
Looks like our flash messages need some CSS work. :)

screenshot 2018-10-29 at 7 33 05 pm

### PR DESCRIPTION
**Pull request by arc9693**
Closes #12

### CODE REVIEW

**Comment by arc9693** [comment]
@saurabhshri Please review.

**Comment by saurabhshri** [comment]
Could you please add screenshots with preview, here?

**Comment by arc9693** [comment]
screenshot from 2018-11-16 14-57-03
<br>
screenshot from 2018-11-16 15-59-03

**Comment by arc9693** [comment]
screenshot from 2018-11-16 16-04-20

**Comment by saurabhshri** [comment]
Excellent, they are a little off in mobile phone resolutions, but that can be looked into later! :) 

screenshot 2018-11-16 at 4 34 48 pm

Thank you for the changes.

**Pull request merged**
